sudo: false
language: java
jdk: oraclejdk8
before_script:
  - npm install -g bower
  - bower install
before_install:
- chmod +x gradlew
install: ./gradlew assemble --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  buildpack: gradle
  app: price-feed-ether-camp
  api_key:
    secure: AAyVf6+oCn0W64H+JDaW0/TDmQz2KoOCav3WNqejiEhjV6mXZBFDfmh829p7ienzI5sNpL1x6OwKbLH1e1YwK05dDzWi73Pzz/JFywLCwzmKJRBPlHFu7sP7St+ypCbEpmooz/rKXtq1xUkb0ohK7BtFovwSDo9GIDeoCtJ4muuFg79Q4xmiLJmejFj2hUglvFAnHy3L31PmJfRF6V86nLKLragF55pmThLqLmajEomABw1BRBEnHjLR3n4SvmiRyTROKdtwARv5x1KkcHV1X40brEoLOIXzLhfT6rAwUg8j+XVB7Ei12Vzz+u963CYmBEj6AzuaALQ84G/N5t4HAr9Y8HDjVjlSqhUThZ9mStwb3rENEfmYGdkUvcmn2ilnMV7h0YogsUwwnzNIRy6VM1nbFwGYN9btO6AbecyfaayZAY8GJll7+9pKttmVY/Psu/fPibg+SecMnHMM2YdfCNwFVsLxFfwboKS/AQF2VMOLoeIqIJdR7rsLTnv8IS6D0DtkDnD4+Q7q586+/QUHCobUQJDJRGzsBL8dwJ1odx7m7RErcHWvFsHTkJRMbNGt/y7q6w2s72EisNcWdrCvtGrUa7TOjbZydUJ50is9BdS+0JgLiHm1cQ3SomDs7ml8Boug/jJ6VIXVALEu1iQjUXGXHzcXdD3Z4URaLOBeBHA=
