sudo: false
language: java
jdk: oraclejdk8
before_script:
- npm install -g bower
- bower install
before_install:
- chmod +x gradlew
install: ./gradlew assemble --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  buildpack: gradle
  app: price-feed-ether-camp
  api_key:
    secure: PUzVXeTcAuKbFgwGhb1vRRo1GwWMyLFYHhxg3U5HC9X9ovmX5It6YyVqWt+WVmtADL3BSBq5/9GGIfamVHfsyDcYaErgVFenQjb0V9VZkBIMa2mYtm2nYvZXf3knlGYTCblhRUcGfLgySuaNxwWH9YRQrEBtwJwjX6P/MM+D/6v9AHj7dh7ajWLuZSYyP+TJFnWEswE+soZmKU/Q2CHGUVVdHMFToQ7cF8xIUW/YfBAhaFKWGKRRaADsSRpWbSnn+N4+C8/JrX+H2vmtnXQS27XHEjJexqzQGPEes4uEf3bvLq12XkbL8II84Sj0ETNPhf+uh24iKwMDASB3VLJysOg3zTGzFWG5elqW7J2oyNLI0F+4+oskBhHhtg/RGmeIfXGMrTaXd5CSEz0yVWhWHv4x0KTyCT+rcuGxwwx57GPXEZlJ5Sl84QTaOhjW+PjSyeyKBEia5EvOpTbEokaWTPK9VY61n6OVsQDONFzwNWUWgKppnKTet725DayzrBqWpzkwB3Rwq+j3pRk1hqJIZxIb4WqVnHdh7RIwwevSyNwbePomwv5nBswcr6oxWiofMqpAeHekbNrWUfLz/qBVHCpEqheFjY6ID2HGE1OEfdGqs5oov0ufLbV6Sp153eC9+uYUmDkAMvmGqBEoRO77WXFHAHs7L1kBi6Gn2I0OFV8=
